%YAML 1.2
---
name: 'kb1-64x6'                       # ideally no spaces
gpu: 0                                 # gpu id to process on

dataset: 
  num_chunks: 100000                   # nof chunks to parse (new to old)
  train_ratio: 0.90                    # trainingset ratio
  input: '/path/to/chunks/*/draw/'     # supports glob

training:
    batch_size: 2048
    total_steps: 140000
    shuffle_size: 524288
    lr_values:
        - 0.02
        - 0.002
        - 0.0005
    lr_boundaries:
        - 100000
        - 130000
    policy_loss_weight: 1.0
    value_loss_weight: 1.0
    path: '/path/to/store/networks'

model:
  filters: 64
  residual_blocks: 6
...
